# Generated by Django 3.2.6 on 2021-08-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(default='This is a default value'),
            preserve_default=False,
        ),
    ]
